# Use an official Python base image
FROM python:3.11

# Set the working directory
WORKDIR /app

# Install Jupyter
RUN pip install gunicorn requests flask jsonify

# Copy the notebook file into the container
COPY app.py /app/

# Expose port 8000
EXPOSE 8000

# Command to execute the notebook directly
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]
