# fly.toml app configuration file generated for assignment-service on 2025-04-24T11:48:54-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'assignment-service'
primary_region = 'sea'

[build]

[env]
  PORT = '8080'
  FLY_ORG="personal"
  COMMON_BUCKET="snakeapi-deployment-test-bucket"
  AWS_ACCESS_KEY_ID="tid__NSmOVaGknqitaCySppZjqVTgJSdDFnFbWcQllkC_juHwkbQZO"
  AWS_SECRET_ACCESS_KEY="tsec_6Bz1aMbfYQftuq5WfIVEDZkHwskU4MMjVywdtxSP6uxetEBvkSC2VHI9HfTeDgHr4D6kiz"
  AWS_ENDPOINT_URL_S3="https://fly.storage.tigris.dev"
  AWS_REGION="auto"
  FLY_API_BASE_URL = "https://api.machines.dev/v1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
