# fly.toml app configuration file generated for assignment-service on 2025-05-20T12:51:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'assignment-service'
primary_region = 'sea'

[build]

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  ports = []  # ✅ No public ports = no public IP

  [services.concurrency]
    type = 'requests'
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
