app = "gameboard-service-aged-glitter-8141"
primary_region = "sea"

[env]
  PORT = "3005"

[build]

[http_service]
  internal_port = 3005
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
