FROM python:3.11-slim
WORKDIR /app

RUN pip install --no-cache-dir jupyter flask awscli flask_cors nbconvert nbformat

COPY entrypoint.sh .
COPY notebook.ipynb .

RUN chmod +x entrypoint.sh

ENV PORT=3006
EXPOSE 3006

CMD ["./entrypoint.sh"]
